const wordList = [
    { word: "guitar", hint: "A musical instrument with strings." },
    { word: "oxygen", hint: "A colorless, odorless gas essential for life." },
    { word: "mountain", hint: "A large natural elevation of the Earth's surface." },
    { word: "history", hint: "The study of past events and human civilization." },
    { word: "diamond", hint: "A precious gemstone known for its brilliance and hardness." },
    { word: "dance", hint: "A rhythmic movement of the body often performed to music." },
    { word: "galaxy", hint: "A vast system of stars, gas, and dust held together by gravity." },
    { word: "volcano", hint: "A mountain or hill with a vent through which lava, rock fragments, hot vapor, and gas are ejected." },
    { word: "novel", hint: "A long work of fiction, typically with a complex plot and characters." },
    { word: "sculpture", hint: "A three-dimensional art form created by shaping or combining materials." },
    { word: "rainbow", hint: "A meteorological phenomenon that is caused by reflection, refraction, and dispersion of light." },
    { word: "piano", hint: "A musical instrument played by pressing keys that cause hammers to strike strings." },
    { word: "vacation", hint: "A period of time devoted to pleasure, rest, or relaxation." },
    { word: "fantasy", hint: "A genre of imaginative fiction involving magic and supernatural elements." },
    { word: "planet", hint: "A celestial body that orbits a star and does not produce light of its own." },
    { word: "tropical", hint: "Relating to or situated in the region between the Tropic of Cancer and the Tropic of Capricorn." },
    { word: "enigma", hint: "Something that is mysterious, puzzling, or difficult to understand." },
    { word: "paradox", hint: "A statement or situation that contradicts itself or defies intuition." },
    { word: "whisper", hint: "To speak very softly or quietly, often in a secretive manner." },
    { word: "shadow", hint: "A dark area or shape produced by an object blocking the light." },
    { word: "curiosity", hint: "A strong desire to know or learn something." },
    { word: "unpredictable", hint: "Not able to be foreseen or known beforehand; uncertain." },
    { word: "obfuscate", hint: "To confuse or bewilder someone; to make something unclear or difficult to understand." },
    { word: "unveil", hint: "To make known or reveal something previously secret or unknown." },
    { word: "vibrant", hint: "Full of energy, brightness, and life." },
    { word: "jungle", hint: "A dense forest in a tropical region." },
    { word: "bridge", hint: "A structure built to span a physical obstacle, like a river." },
    { word: "sword", hint: "A weapon with a long blade used in combat." },
    { word: "harvest", hint: "The process of gathering ripe crops from the fields." },
    { word: "quartz", hint: "A hard mineral often used in watches and electronics." },
    { word: "flight", hint: "The action or process of flying through the air." },
    { word: "bronze", hint: "A metal alloy consisting of copper and tin." },
    { word: "island", hint: "A piece of land surrounded by water." },
    { word: "globe", hint: "A spherical model of Earth." },
    { word: "knight", hint: "A warrior of noble rank in medieval times." },
    { word: "python", hint: "A large non-venomous snake, or a popular programming language." },
    { word: "sphinx", hint: "A mythical creature with a lion’s body and a human head." },
    { word: "velcro", hint: "A fastener with hook-and-loop strips." },
    { word: "jewel", hint: "A precious stone or gem." },
    { word: "hound", hint: "A type of dog trained for hunting." },
    { word: "crisp", hint: "Firm, dry, and brittle in texture." },
    { word: "plough", hint: "A farming tool used to prepare soil." },
    { word: "ivory", hint: "A hard, white material from elephant tusks." },
    { word: "quake", hint: "A sudden shaking of the ground due to tectonic activity." },
    { word: "fjord", hint: "A long, narrow, deep inlet of the sea between high cliffs." },
    { word: "mythic", hint: "Relating to or resembling myths or legends." },
];
